  ---
matrix:
  include:
    - language: python
      sudo: required
      services:
      - docker
      script:
      - cd database
      - docker build -t mysql_sportify .
    
    - language: node_js
      os: linux
      arch: arm64
      dist: bionic
      node_js:
        - 10
      cache:
        yarn: true
        directories:
          - node_modules
      before_install:
        - cd frontend
      script:
        - yarn build

    - language: node_js
      os: linux
      arch: arm64
      dist: bionic
      node_js:
        - 10
      cache:
        yarn: true
        directories:
          - node_modules
      before_install:
        - cd backend
      script:
        - yarn build
