language: node_js
node_js:
  - 10

---
matrix:
  include:
    - cache:
        yarn: true
        directories:
          - node_modules
    
      before_install:
        - "cd frontend"
    
      script:
        - yarn build

    - cache:
        yarn: true
        directories:
          - node_modules
    
      before_install:
        - "cd backend"
    
      script:
        - yarn build