---
matrix:
  include:
    - language: python
      sudo: required
      services:
      - docker
      script:
      - cd database
      - docker build -t mysql_sportify .
      - docker run -d -p 3306:3306 --name mysql_sportify mysql_sportify:latest
      - sleep 90
      - docker exec -i mysql_sportify mysql -uroot -ppassword  <<< "SELECT 1"
      - docker stop mysql_sportify

    - language: node_js
      node_js:
        - 10
      cache:
        yarn: true
        directories:
          - node_modules
      before_install:
        - cd frontend
      script:
        - yarn build

    - language: node_js
      node_js:
        - 10
      cache:
        yarn: true
        directories:
          - node_modules
      before_install:
        - cd backend
      script:
        - yarn build
